{
 "title": "Dash 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "La Liste Des Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT  job_name AS Job_Name FROM batch_job_instance "
    }
   ]
  },
  {
   "title": "La Liste Des Instances",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT job_name, COUNT(*) AS instance_count\r\nFROM batch_job_instance \r\nGROUP BY job_name;"
    }
   ]
  },
  {
   "title": "Le nom de chaque batch avec sa durée ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  b.job_name, j.job_execution_id,j.start_time, j.end_time - j.start_time AS duration\r\nFROM batch_job_execution j\r\nJOIN batch_job_instance b ON j.job_instance_id = b.job_instance_id\r\nWHERE j.end_time IS NOT NULL;\r\n"
    }
   ]
  },
  {
   "title": "Status Job executions ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status, COUNT(*) as count\r\nFROM batch_job_execution \r\nWHERE status IN ('COMPLETED', 'FAILED')\r\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "STATUS",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT status as \"Status\", COUNT(*) as \"Count\"\r\nFROM batch_job_execution \r\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "Le nombre de batches en cours d'exécution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as count\r\nFROM batch_job_execution \r\nWHERE status = 'STARTED';"
    }
   ]
  }
 ]
}